CREATE DATABASE IF NOT EXISTS nephro_users_db;
CREATE DATABASE IF NOT EXISTS clinical_db;
CREATE DATABASE IF NOT EXISTS hospitalization_db;
CREATE DATABASE IF NOT EXISTS diagnostic_db;
CREATE DATABASE IF NOT EXISTS dialysis_db;
CREATE DATABASE IF NOT EXISTS pharmacy_db;
CREATE DATABASE IF NOT EXISTS order_db;
