server:
  port: 8079

spring:
  application:
    name: clinical-service

  datasource:
    url: jdbc:mysql://localhost:3306/clinical_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      api-key: ${GEMINI_API_KEY:}
      enabled: true
      chat:
        options:
          model: gemini-2.5-flash

user:
  service:
    base-url: http://localhost:8069/api/users